AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - Gemfile
    - Rakefile
  IgnoredMethods:
    - describe
    - expect_with
    - mock_with
    - pp
    - puts
    - raise
    - require
    - to
